spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: mongodb://yoon9531:testpasswordadmin1234@localhost:27017/writing_db?authSource=admin
  datasource:
    url: jdbc:mysql://localhost:3306/writing_db?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    com.writingboard.server: info
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.redis: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 7200000   # 2hours (ms 단위)
  refresh-expiration: 604800000 # 7일 (ms 단위)

cloud:
  r2:
    credentials:
      access-key: "3458beceefc473d77403057a9b2e2aea"
      secret-key: "0cacd5df8f92a7dd347ff9609c440961c82086ea157c44029482042f44f4c920"
    endpoint: "https://524c46e0afa2f741cf42269fdc20d736.r2.cloudflarestorage.com"
    bucket: "chalkchalk"
    region: "auto"